In [1]:
import numpy as np
import pandas as pd
import os


In [2]:
def read_npy(filepath):
    with open(filepath, 'rb') as f:
        data = np.load(f)
    return data

In [3]:
import pickle

def save_pickle(directory, filename, file_to_save):
#     make_dir_if_not_exists(directory)
    
    with open(os.path.join(directory, filename), 'wb') as handle:
        pickle.dump(file_to_save, handle, protocol=pickle.HIGHEST_PROTOCOL)

### All Shared Stanford test set

In [4]:
stanford_test_image_path = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/stanford_A4C_image.npy'
stanford_test_label_path = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/stanford_A4C_label.npy'


In [5]:
stanford_test_images = read_npy(stanford_test_image_path)
stanford_test_labels = read_npy(stanford_test_label_path)


In [6]:
print('stanford_test_images: {}, stanford_test_labels: {}'.format(stanford_test_images.shape , stanford_test_labels.shape ))


stanford_test_images: (10030, 112, 112, 3), stanford_test_labels: (10030,)


In [7]:
set(stanford_test_labels)


{2}

In [8]:
stanford_test_set = {"images":stanford_test_images, "labels":stanford_test_labels}


In [9]:
#save the test set
all_shared_stanford_testset_path = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/realistic-ssl-evaluation-pytorch_RE/ML_DATA/TMED2/unnormalized_HWC/echo/all_shared_stanford_testset'
# np.save(os.path.join(data_seed0_shared_testset_path, 'test.npy'), seed0_test_set)
save_pickle(all_shared_stanford_testset_path, 'stanford_A4C.npy', stanford_test_set)


## Seed0

#### step0: filter out the instance for A4CorA2CorOther from the test set of seed0

In [4]:
seed0_test_image_path = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/ViewClassifier/npy_seed0/shared_test_this_seed/test_image.npy'
seed0_test_label_path = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/ViewClassifier/npy_seed0/shared_test_this_seed/test_label.npy'


In [5]:
seed0_test_images = read_npy(seed0_test_image_path)
seed0_test_labels = read_npy(seed0_test_label_path)

In [6]:
print('seed0_test_images: {}, seed0_test_labels: {}'.format(seed0_test_images.shape , seed0_test_labels.shape ))


seed0_test_images: (3602, 112, 112, 3), seed0_test_labels: (3602,)


In [7]:
set(seed0_test_labels)

{0, 1, 2, 3, 4}

In [8]:
seed0_test_images

array([[[[0, 0, 0],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [1, 1, 1],
         [0, 0, 0],
         [0, 0, 0]],

        ...,

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]],


       [[[0, 0, 0],
         [1, 1, 1],
         [1, 1, 1],
         ...,
         [0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0,

In [10]:
seed0_test_labels

array([0, 0, 0, ..., 4, 4, 4])

In [9]:
seed0_test_labels

array([0, 0, 0, ..., 4, 4, 4])

In [8]:
NotA4CorA2CorOther_mask = seed0_test_labels!=4

In [9]:
NotA4CorA2CorOther_mask

array([ True,  True,  True, ..., False, False, False])

In [10]:
print('After filtering out A4CorA2CorOther:')
print('seed0_test_images[NotA4CorA2CorOther_mask]: {}, seed0_test_labels[NotA4CorA2CorOther_mask]: {}'.format(seed0_test_images[NotA4CorA2CorOther_mask].shape , seed0_test_labels[NotA4CorA2CorOther_mask].shape ))


After filtering out A4CorA2CorOther:
seed0_test_images[NotA4CorA2CorOther_mask]: (2104, 112, 112, 3), seed0_test_labels[NotA4CorA2CorOther_mask]: (2104,)


In [11]:
seed0_test_set = {"images":seed0_test_images[NotA4CorA2CorOther_mask], "labels":seed0_test_labels[NotA4CorA2CorOther_mask]}


In [12]:
#save the test set
data_seed0_shared_testset_path = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/realistic-ssl-evaluation-pytorch_RE/ML_DATA/TMED2/unnormalized_HWC/echo/data_seed0/this_seed_shared_testset'
# np.save(os.path.join(data_seed0_shared_testset_path, 'test.npy'), seed0_test_set)
save_pickle(data_seed0_shared_testset_path, 'test.npy', seed0_test_set)


### DEV479

In [3]:
seed0_DEV479_dir = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/ViewClassifier/npy_seed0/DEV479'


#### step1: concatenate the already processed npy file for train set

In [4]:

seed0_DEV479_train_A4C_image_path = os.path.join(seed0_DEV479_dir, 'train_A4C_image.npy')
seed0_DEV479_train_A4C_label_path = os.path.join(seed0_DEV479_dir, 'train_A4C_label.npy')

seed0_DEV479_train_A2C_image_path = os.path.join(seed0_DEV479_dir, 'train_A2C_image.npy')
seed0_DEV479_train_A2C_label_path = os.path.join(seed0_DEV479_dir, 'train_A2C_label.npy')

seed0_DEV479_train_PLAX_image_path = os.path.join(seed0_DEV479_dir, 'train_PLAX_image.npy')
seed0_DEV479_train_PLAX_label_path = os.path.join(seed0_DEV479_dir, 'train_PLAX_label.npy')

seed0_DEV479_train_PSAX_image_path = os.path.join(seed0_DEV479_dir, 'train_PSAX_image.npy')
seed0_DEV479_train_PSAX_label_path = os.path.join(seed0_DEV479_dir, 'train_PSAX_label.npy')



In [5]:
seed0_DEV479_train_A4C_images = read_npy(seed0_DEV479_train_A4C_image_path)
seed0_DEV479_train_A4C_labels = read_npy(seed0_DEV479_train_A4C_label_path)

seed0_DEV479_train_A2C_images = read_npy(seed0_DEV479_train_A2C_image_path)
seed0_DEV479_train_A2C_labels = read_npy(seed0_DEV479_train_A2C_label_path)

seed0_DEV479_train_PLAX_images = read_npy(seed0_DEV479_train_PLAX_image_path)
seed0_DEV479_train_PLAX_labels = read_npy(seed0_DEV479_train_PLAX_label_path)

seed0_DEV479_train_PSAX_images = read_npy(seed0_DEV479_train_PSAX_image_path)
seed0_DEV479_train_PSAX_labels = read_npy(seed0_DEV479_train_PSAX_label_path)


In [6]:
print('seed0_DEV479_train_PLAX_images: {}, seed0_DEV479_train_PLAX_labels: {}'.format(seed0_DEV479_train_PLAX_images.shape, seed0_DEV479_train_PLAX_labels.shape))
print('seed0_DEV479_train_PSAX_images: {}, seed0_DEV479_train_PSAX_labels: {}'.format(seed0_DEV479_train_PSAX_images.shape, seed0_DEV479_train_PSAX_labels.shape))
print('seed0_DEV479_train_A4C_images: {}, seed0_DEV479_train_A4C_labels: {}'.format(seed0_DEV479_train_A4C_images.shape, seed0_DEV479_train_A4C_labels.shape))
print('seed0_DEV479_train_A2C_images: {}, seed0_DEV479_train_A2C_labels: {}'.format(seed0_DEV479_train_A2C_images.shape, seed0_DEV479_train_A2C_labels.shape))



seed0_DEV479_train_PLAX_images: (5413, 112, 112, 3), seed0_DEV479_train_PLAX_labels: (5413,)
seed0_DEV479_train_PSAX_images: (2002, 112, 112, 3), seed0_DEV479_train_PSAX_labels: (2002,)
seed0_DEV479_train_A4C_images: (3750, 112, 112, 3), seed0_DEV479_train_A4C_labels: (3750,)
seed0_DEV479_train_A2C_images: (2827, 112, 112, 3), seed0_DEV479_train_A2C_labels: (2827,)


In [8]:
seed0_DEV479_train_images = np.concatenate((seed0_DEV479_train_A4C_images,\
                                            seed0_DEV479_train_A2C_images,\
                                            seed0_DEV479_train_PLAX_images,\
                                            seed0_DEV479_train_PSAX_images), axis=0)

seed0_DEV479_train_labels = np.concatenate((seed0_DEV479_train_A4C_labels,\
                                            seed0_DEV479_train_A2C_labels,\
                                            seed0_DEV479_train_PLAX_labels,\
                                            seed0_DEV479_train_PSAX_labels), axis=0)


In [9]:
print('seed0_DEV479_train_images: {}, seed0_DEV479_train_labels: {}'.format(seed0_DEV479_train_images.shape, seed0_DEV479_train_labels.shape))

assert len(seed0_DEV479_train_images) == len(seed0_DEV479_train_labels) == len(seed0_DEV479_train_A4C_images) + len(seed0_DEV479_train_A2C_images) +\
                                                                           len(seed0_DEV479_train_PLAX_images) + len(seed0_DEV479_train_PSAX_images)



seed0_DEV479_train_images: (13992, 112, 112, 3), seed0_DEV479_train_labels: (13992,)


In [10]:
seed0_DEV479_train_set = {"images":seed0_DEV479_train_images, "labels":seed0_DEV479_train_labels}


In [11]:
#save the test set
data_seed0_DEV479_trainset_path = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/realistic-ssl-evaluation-pytorch_RE/ML_DATA/TMED2/unnormalized_HWC/echo/data_seed0/DEV479'
# np.save(os.path.join(data_seed0_DEV479_trainset_path, 'train.npy'), seed0_DEV479_train_set)
save_pickle(data_seed0_DEV479_trainset_path, 'train.npy', seed0_DEV479_train_set)


#### step2: filter out the instance for A4CorA2CorOther from the val set of seed0 DEV479

In [4]:
seed0_DEV479_val_image_path = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/ViewClassifier/npy_seed0/DEV479/val_image.npy'
seed0_DEV479_val_label_path = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/ViewClassifier/npy_seed0/DEV479/val_label.npy'


In [5]:
seed0_DEV479_val_images = read_npy(seed0_DEV479_val_image_path)
seed0_DEV479_val_labels = read_npy(seed0_DEV479_val_label_path)

In [6]:
print('seed0_DEV479_val_images: {}, seed0_DEV479_val_labels: {}'.format(seed0_DEV479_val_images.shape , seed0_DEV479_val_labels.shape ))
 

seed0_DEV479_val_images: (3602, 112, 112, 3), seed0_DEV479_val_labels: (3602,)


In [7]:
set(seed0_DEV479_val_labels)

{0, 1, 2, 3, 4}

In [8]:
NotA4CorA2CorOther_mask = seed0_DEV479_val_labels!=4

In [9]:
NotA4CorA2CorOther_mask

array([ True,  True,  True, ..., False, False, False])

In [10]:
print('After filtering out A4CorA2CorOther:')
print('seed0_DEV479_val_images[NotA4CorA2CorOther_mask]: {}, seed0_DEV479_val_labels[NotA4CorA2CorOther_mask]: {}'.format(seed0_DEV479_val_images[NotA4CorA2CorOther_mask].shape , seed0_DEV479_val_labels[NotA4CorA2CorOther_mask].shape ))


After filtering out A4CorA2CorOther:
seed0_DEV479_val_images[NotA4CorA2CorOther_mask]: (2007, 112, 112, 3), seed0_DEV479_val_labels[NotA4CorA2CorOther_mask]: (2007,)


In [11]:
seed0_DEV479_val_set = {"images":seed0_DEV479_val_images[NotA4CorA2CorOther_mask], "labels":seed0_DEV479_val_labels[NotA4CorA2CorOther_mask]}


In [12]:
#save the val set
data_seed0_DEV479_valset_path = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/realistic-ssl-evaluation-pytorch_RE/ML_DATA/TMED2/unnormalized_HWC/echo/data_seed0/DEV479'
# np.save(os.path.join(data_seed0_DEV479_valset_path, 'val.npy'),seed0_DEV479_val_set)
save_pickle(data_seed0_DEV479_valset_path, 'val.npy', seed0_DEV479_val_set)



### DEV165

In [7]:
seed0_DEV165_dir = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/ViewClassifier/npy_seed0/DEV165'


#### step1: concatenate the already processed npy file for train set

In [8]:

seed0_DEV165_train_A4C_image_path = os.path.join(seed0_DEV165_dir, 'train_A4C_image.npy')
seed0_DEV165_train_A4C_label_path = os.path.join(seed0_DEV165_dir, 'train_A4C_label.npy')

seed0_DEV165_train_A2C_image_path = os.path.join(seed0_DEV165_dir, 'train_A2C_image.npy')
seed0_DEV165_train_A2C_label_path = os.path.join(seed0_DEV165_dir, 'train_A2C_label.npy')

seed0_DEV165_train_PLAX_image_path = os.path.join(seed0_DEV165_dir, 'train_PLAX_image.npy')
seed0_DEV165_train_PLAX_label_path = os.path.join(seed0_DEV165_dir, 'train_PLAX_label.npy')

seed0_DEV165_train_PSAX_image_path = os.path.join(seed0_DEV165_dir, 'train_PSAX_image.npy')
seed0_DEV165_train_PSAX_label_path = os.path.join(seed0_DEV165_dir, 'train_PSAX_label.npy')



In [9]:
seed0_DEV165_train_A4C_images = read_npy(seed0_DEV165_train_A4C_image_path)
seed0_DEV165_train_A4C_labels = read_npy(seed0_DEV165_train_A4C_label_path)

seed0_DEV165_train_A2C_images = read_npy(seed0_DEV165_train_A2C_image_path)
seed0_DEV165_train_A2C_labels = read_npy(seed0_DEV165_train_A2C_label_path)

seed0_DEV165_train_PLAX_images = read_npy(seed0_DEV165_train_PLAX_image_path)
seed0_DEV165_train_PLAX_labels = read_npy(seed0_DEV165_train_PLAX_label_path)

seed0_DEV165_train_PSAX_images = read_npy(seed0_DEV165_train_PSAX_image_path)
seed0_DEV165_train_PSAX_labels = read_npy(seed0_DEV165_train_PSAX_label_path)


In [10]:
print('seed0_DEV165_train_PLAX_images: {}, seed0_DEV165_train_PLAX_labels: {}'.format(seed0_DEV165_train_PLAX_images.shape, seed0_DEV165_train_PLAX_labels.shape))
print('seed0_DEV165_train_PSAX_images: {}, seed0_DEV165_train_PSAX_labels: {}'.format(seed0_DEV165_train_PSAX_images.shape, seed0_DEV165_train_PSAX_labels.shape))
print('seed0_DEV165_train_A4C_images: {}, seed0_DEV165_train_A4C_labels: {}'.format(seed0_DEV165_train_A4C_images.shape, seed0_DEV165_train_A4C_labels.shape))
print('seed0_DEV165_train_A2C_images: {}, seed0_DEV165_train_A2C_labels: {}'.format(seed0_DEV165_train_A2C_images.shape, seed0_DEV165_train_A2C_labels.shape))


seed0_DEV165_train_PLAX_images: (1867, 112, 112, 3), seed0_DEV165_train_PLAX_labels: (1867,)
seed0_DEV165_train_PSAX_images: (698, 112, 112, 3), seed0_DEV165_train_PSAX_labels: (698,)
seed0_DEV165_train_A4C_images: (1281, 112, 112, 3), seed0_DEV165_train_A4C_labels: (1281,)
seed0_DEV165_train_A2C_images: (950, 112, 112, 3), seed0_DEV165_train_A2C_labels: (950,)


In [8]:
seed0_DEV165_train_images = np.concatenate((seed0_DEV165_train_A4C_images,\
                                            seed0_DEV165_train_A2C_images,\
                                            seed0_DEV165_train_PLAX_images,\
                                            seed0_DEV165_train_PSAX_images), axis=0)

seed0_DEV165_train_labels = np.concatenate((seed0_DEV165_train_A4C_labels,\
                                            seed0_DEV165_train_A2C_labels,\
                                            seed0_DEV165_train_PLAX_labels,\
                                            seed0_DEV165_train_PSAX_labels), axis=0)


In [9]:
print('seed0_DEV165_train_images: {}, seed0_DEV165_train_labels: {}'.format(seed0_DEV165_train_images.shape, seed0_DEV165_train_labels.shape))

assert len(seed0_DEV165_train_images) == len(seed0_DEV165_train_labels) == len(seed0_DEV165_train_A4C_images) + len(seed0_DEV165_train_A2C_images) +\
                                                                           len(seed0_DEV165_train_PLAX_images) + len(seed0_DEV165_train_PSAX_images)



seed0_DEV165_train_images: (4796, 112, 112, 3), seed0_DEV165_train_labels: (4796,)


In [10]:
seed0_DEV165_train_set = {"images":seed0_DEV165_train_images, "labels":seed0_DEV165_train_labels}


In [11]:
#save the test set
data_seed0_DEV165_trainset_path = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/realistic-ssl-evaluation-pytorch_RE/ML_DATA/TMED2/unnormalized_HWC/echo/data_seed0/DEV165'
# np.save(os.path.join(data_seed0_DEV165_trainset_path, 'train.npy'), seed0_DEV165_train_set)
save_pickle(data_seed0_DEV165_trainset_path, 'train.npy', seed0_DEV165_train_set)


#### step2: filter out the instance for A4CorA2CorOther from the val set of seed0 DEV479

In [4]:
seed0_DEV165_val_image_path = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/ViewClassifier/npy_seed0/DEV165/val_image.npy'
seed0_DEV165_val_label_path = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/ViewClassifier/npy_seed0/DEV165/val_label.npy'


In [5]:
seed0_DEV165_val_images = read_npy(seed0_DEV165_val_image_path)
seed0_DEV165_val_labels = read_npy(seed0_DEV165_val_label_path)

In [6]:
print('seed0_DEV165_val_images: {}, seed0_DEV165_val_labels: {}'.format(seed0_DEV165_val_images.shape , seed0_DEV165_val_labels.shape ))



seed0_DEV165_val_images: (1274, 112, 112, 3), seed0_DEV165_val_labels: (1274,)


In [7]:
set(seed0_DEV165_val_labels)

{0, 1, 2, 3, 4}

In [8]:
NotA4CorA2CorOther_mask = seed0_DEV165_val_labels!=4

In [9]:
NotA4CorA2CorOther_mask

array([ True,  True,  True, ..., False, False, False])

In [10]:
print('After filtering out A4CorA2CorOther:')
print('seed0_DEV165_val_images[NotA4CorA2CorOther_mask]: {}, seed0_DEV165_val_labels[NotA4CorA2CorOther_mask]: {}'.format(seed0_DEV165_val_images[NotA4CorA2CorOther_mask].shape , seed0_DEV165_val_labels[NotA4CorA2CorOther_mask].shape ))


After filtering out A4CorA2CorOther:
seed0_DEV165_val_images[NotA4CorA2CorOther_mask]: (735, 112, 112, 3), seed0_DEV165_val_labels[NotA4CorA2CorOther_mask]: (735,)


In [11]:
seed0_DEV165_val_set = {"images":seed0_DEV165_val_images[NotA4CorA2CorOther_mask], "labels":seed0_DEV165_val_labels[NotA4CorA2CorOther_mask]}


In [12]:
#save the val set
data_seed0_DEV165_valset_path = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/realistic-ssl-evaluation-pytorch_RE/ML_DATA/TMED2/unnormalized_HWC/echo/data_seed0/DEV165'
# np.save(os.path.join(data_seed0_DEV165_valset_path, 'val.npy'),seed0_DEV165_val_set)
save_pickle(data_seed0_DEV165_valset_path, 'val.npy', seed0_DEV165_val_set)



### DEV56

In [11]:
seed0_DEV56_dir = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/ViewClassifier/npy_seed0/DEV56'


#### step1: concatenate the already processed npy file for train set

In [12]:

seed0_DEV56_train_A4C_image_path = os.path.join(seed0_DEV56_dir, 'train_A4C_image.npy')
seed0_DEV56_train_A4C_label_path = os.path.join(seed0_DEV56_dir, 'train_A4C_label.npy')

seed0_DEV56_train_A2C_image_path = os.path.join(seed0_DEV56_dir, 'train_A2C_image.npy')
seed0_DEV56_train_A2C_label_path = os.path.join(seed0_DEV56_dir, 'train_A2C_label.npy')

seed0_DEV56_train_PLAX_image_path = os.path.join(seed0_DEV56_dir, 'train_PLAX_image.npy')
seed0_DEV56_train_PLAX_label_path = os.path.join(seed0_DEV56_dir, 'train_PLAX_label.npy')

seed0_DEV56_train_PSAX_image_path = os.path.join(seed0_DEV56_dir, 'train_PSAX_image.npy')
seed0_DEV56_train_PSAX_label_path = os.path.join(seed0_DEV56_dir, 'train_PSAX_label.npy')



In [13]:
seed0_DEV56_train_A4C_images = read_npy(seed0_DEV56_train_A4C_image_path)
seed0_DEV56_train_A4C_labels = read_npy(seed0_DEV56_train_A4C_label_path)

seed0_DEV56_train_A2C_images = read_npy(seed0_DEV56_train_A2C_image_path)
seed0_DEV56_train_A2C_labels = read_npy(seed0_DEV56_train_A2C_label_path)

seed0_DEV56_train_PLAX_images = read_npy(seed0_DEV56_train_PLAX_image_path)
seed0_DEV56_train_PLAX_labels = read_npy(seed0_DEV56_train_PLAX_label_path)

seed0_DEV56_train_PSAX_images = read_npy(seed0_DEV56_train_PSAX_image_path)
seed0_DEV56_train_PSAX_labels = read_npy(seed0_DEV56_train_PSAX_label_path)


In [14]:
print('seed0_DEV56_train_PLAX_images: {}, seed0_DEV56_train_PLAX_labels: {}'.format(seed0_DEV56_train_PLAX_images.shape, seed0_DEV56_train_PLAX_labels.shape))
print('seed0_DEV56_train_PSAX_images: {}, seed0_DEV56_train_PSAX_labels: {}'.format(seed0_DEV56_train_PSAX_images.shape, seed0_DEV56_train_PSAX_labels.shape))
print('seed0_DEV56_train_A4C_images: {}, seed0_DEV56_train_A4C_labels: {}'.format(seed0_DEV56_train_A4C_images.shape, seed0_DEV56_train_A4C_labels.shape))
print('seed0_DEV56_train_A2C_images: {}, seed0_DEV56_train_A2C_labels: {}'.format(seed0_DEV56_train_A2C_images.shape, seed0_DEV56_train_A2C_labels.shape))



seed0_DEV56_train_PLAX_images: (632, 112, 112, 3), seed0_DEV56_train_PLAX_labels: (632,)
seed0_DEV56_train_PSAX_images: (239, 112, 112, 3), seed0_DEV56_train_PSAX_labels: (239,)
seed0_DEV56_train_A4C_images: (405, 112, 112, 3), seed0_DEV56_train_A4C_labels: (405,)
seed0_DEV56_train_A2C_images: (285, 112, 112, 3), seed0_DEV56_train_A2C_labels: (285,)


In [8]:
seed0_DEV56_train_images = np.concatenate((seed0_DEV56_train_A4C_images,\
                                            seed0_DEV56_train_A2C_images,\
                                            seed0_DEV56_train_PLAX_images,\
                                            seed0_DEV56_train_PSAX_images), axis=0)

seed0_DEV56_train_labels = np.concatenate((seed0_DEV56_train_A4C_labels,\
                                            seed0_DEV56_train_A2C_labels,\
                                            seed0_DEV56_train_PLAX_labels,\
                                            seed0_DEV56_train_PSAX_labels), axis=0)


In [9]:
print('seed0_DEV56_train_images: {}, seed0_DEV56_train_labels: {}'.format(seed0_DEV56_train_images.shape, seed0_DEV56_train_labels.shape))

assert len(seed0_DEV56_train_images) == len(seed0_DEV56_train_labels) == len(seed0_DEV56_train_A4C_images) + len(seed0_DEV56_train_A2C_images) +\
                                                                           len(seed0_DEV56_train_PLAX_images) + len(seed0_DEV56_train_PSAX_images)




seed0_DEV56_train_images: (1561, 112, 112, 3), seed0_DEV56_train_labels: (1561,)


In [10]:
seed0_DEV56_train_set = {"images":seed0_DEV56_train_images, "labels":seed0_DEV56_train_labels}


In [11]:
#save the test set
data_seed0_DEV56_trainset_path = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/realistic-ssl-evaluation-pytorch_RE/ML_DATA/TMED2/unnormalized_HWC/echo/data_seed0/DEV56'
# np.save(os.path.join(data_seed0_DEV56_trainset_path, 'train.npy'), seed0_DEV56_train_set)
save_pickle(data_seed0_DEV56_trainset_path, 'train.npy', seed0_DEV56_train_set)


#### step2: filter out the instance for A4CorA2CorOther from the val set of seed0 DEV479

In [4]:
seed0_DEV56_val_image_path = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/ViewClassifier/npy_seed0/DEV56/val_image.npy'
seed0_DEV56_val_label_path = '/cluster/tufts/hugheslab/zhuang12/Echo_ClinicalManualScript_1112/ML_DATA/ViewClassifier/npy_seed0/DEV56/val_label.npy'


In [5]:
seed0_DEV56_val_images = read_npy(seed0_DEV56_val_image_path)
seed0_DEV56_val_labels = read_npy(seed0_DEV56_val_label_path)

In [6]:
print('seed0_DEV56_val_images: {}, seed0_DEV56_val_labels: {}'.format(seed0_DEV56_val_images.shape , seed0_DEV56_val_labels.shape ))



seed0_DEV56_val_images: (350, 112, 112, 3), seed0_DEV56_val_labels: (350,)


In [7]:
set(seed0_DEV56_val_labels)

{0, 1, 2, 3, 4}

In [8]:
NotA4CorA2CorOther_mask = seed0_DEV56_val_labels!=4

In [9]:
NotA4CorA2CorOther_mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [10]:
print('After filtering out A4CorA2CorOther:')
print('seed0_DEV56_val_images[NotA4CorA2CorOther_mask]: {}, seed0_DEV56_val_labels[NotA4CorA2CorOther_mask]: {}'.format(seed0_DEV56_val_images[NotA4CorA2CorOther_mask].shape , seed0_DEV56_val_labels[NotA4CorA2CorOther_mask].shape ))


After filtering out A4CorA2CorOther:
seed0_DEV56_val_images[NotA4CorA2CorOther_mask]: (243, 112, 112, 3), seed0_DEV56_val_labels[NotA4CorA2CorOther_mask]: (243,)


In [11]:
seed0_DEV56_val_set = {"images":seed0_DEV56_val_images[NotA4CorA2CorOther_mask], "labels":seed0_DEV56_val_labels[NotA4CorA2CorOther_mask]}


In [12]:
#save the val set
data_seed0_DEV56_valset_path = '/cluster/tufts/hugheslab/zhuang12/SSL_Contamination/realistic-ssl-evaluation-pytorch_RE/ML_DATA/TMED2/unnormalized_HWC/echo/data_seed0/DEV56'
# np.save(os.path.join(data_seed0_DEV56_valset_path, 'val.npy'),seed0_DEV56_val_set)
save_pickle(data_seed0_DEV56_valset_path, 'val.npy', seed0_DEV56_val_set)
